### ISSUE TITLE
Drag and Drop causes imgui to crash

### ISSUE THREAD

**Issue by MrZoraman** [flyover/imgui-js#11]
This bug is quite easy to reproduce. Just go to the [example page](https://flyover.github.io/imgui-js/example/) and in the demo window: Widgets -> Drag and Drop, and try clicking and dragging one of the boxes. Imgui crashes.

It seems to do this for every browser I've tried: Edge 76.0.152.0, Chrome 74.0.3729.131, whatever safari my friend had on his macbook.

**Comment by flyover** [comment]
Thanks for reporting.  This should be fixed with 7e84193d9bfc01a7d0b79bf9b05473af3d662a66.
