### ISSUE TITLE
Example implementation blurry on High DPI displays

### ISSUE THREAD

**Issue by DoctorGester** [flyover/imgui-js#2]
https://www.khronos.org/webgl/wiki/HandlingHighDPI

**Comment by flyover** [comment]
50df0befcf65f7425a6a936fdee2bb9136df5300

**Comment by DoctorGester** [comment]
@flyover it's not blurry anymore, but it's small :D 
I'm unable to test right now but I think https://github.com/flyover/imgui-js/blob/master/example/imgui_impl.ts#L264-L265 those should use .scrollWidth and .scrollHeight because those supposed to be actual display size (both gl.drawingBufferWidth and gl.canvas.width represent the same thing - internal framebuffer size)

**Comment by flyover** [comment]
aff0e3b9b3a7358e37b337854735f310cb222140

I also had to add a [viewport meta tag](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag#Viewport_width_and_screen_width) to get it to scale correctly.

**Comment by DoctorGester** [comment]
Nice! You would need to rollback your older code which modifies mouse position though because right now it's incorrect.

I'm working on a webassembly version of imgui right now and couldn't figure out a bug with the glViewport call on retina displays (turns out that call wasn't needed), so now I've figured out thanks to your code!

**Comment by flyover** [comment]
6fba14235d1492e35479cfcf5c6817bd7168981c
