### ISSUE TITLE
Bug  ImGui.InputText Not Wrok By UI from keyboard

### ISSUE THREAD

**Issue by wshmaple** [flyover/imgui-js#33]
This Demo https://codepen.io/flyovergames/pen/ejXjXj
`    ImGui.InputText("name", (value = mesh.name) => mesh.name = value);`
UI input by keyborad is not work

BUT Demo https://codepen.io/flyovergames/pen/xYPBaj is OK 

WHY?

**Comment by flyover** [comment]
Thanks for letting me know.  The canvas element needed the tabindex attribute for it to accept keyboard input.

**Comment by wshmaple** [comment]
> Thanks for letting me know. The canvas element needed the tabindex attribute for it to accept keyboard input.

Thanks for fix
Working OK
