### ISSUE TITLE
Example Doesn't Work in Safari (macOS/iOS)

### ISSUE THREAD

**Issue by Francois-Laberge-Bose** [flyover/imgui-js#37]
I get a black screen when going to the demo URL: https://flyover.github.io/imgui-js/example/

<img width="303" alt="Screen Shot 2021-02-01 at 2 06 26 PM" src="https://user-images.githubusercontent.com/34040155/106505831-d8329e00-6496-11eb-9e2e-85754f6cb693.png">

Looks like it tries to use `WebGL2RenderingContext`, which is not available in Safari (macOS or iOS).
<img width="500" alt="Screen Shot 2021-02-01 at 2 07 58 PM" src="https://user-images.githubusercontent.com/34040155/106505867-e54f8d00-6496-11eb-826f-03712f9c7114.png">

**Comment by flyover** [comment]
Yep, thanks for letting me know.; should be fixed now.

**Comment by Francois-Laberge-Bose** [comment]
Wow, fast turn around! On my phone but will verify when I get back to my computer.

**Comment by Francois-Laberge-Bose** [comment]
Confirmed on iOS. Will close if it’s the same on macOS

**Comment by Francois-Laberge-Bose** [comment]
Works on macOS, closing.
