### ISSUE TITLE
Import with webpack

### ISSUE THREAD

**Issue by ch3coohlink** [flyover/imgui-js#4]
I'm trying to use imgui-js with webpack, it do compile, but output "System.register is not supported by webpack." in the browser console, is it necessary to use systemJS to embed imgui-js?

**Comment by LunarMist** [comment]
You shouldn't need systemjs necessarily. As long as you're transpiling the typscript files yourself (via webpack), you should be able to use any module system you want.

**Comment by ch3coohlink** [comment]
@LunarMist So you mean just treat the typescript code as the source and import it with webpack? That should work, but I still wondering is there any way to use this repo as an ordinary npm module (which I can import with webpack or some plugin)? Just curious about that, anyway, thank you.
