### ISSUE TITLE
This code does not correctly save/restore WebGL state

### ISSUE THREAD

**Issue by greggman** [flyover/imgui-js#40]
https://github.com/flyover/imgui-js/blob/e4aeea79e8c30d03803aa7782b34ddaffe9e6939/example/src/imgui_impl.ts#L552

The attribute state is being overwritten and then not restored.

**Comment by flyover** [comment]
Thanks for the bug report.  I've updated the example to more closely match the OpenGL 3 example.  See a1a29057476ab50b5f1d8c5e4eb2b1021a632a0b.
